id: I844E8AB0
source: https://library.bdrc.io
source_file: null
initial_creation_type: ocr
imported: '2020-03-10T09:01:11+00:00'
last_modified: '2022-06-09T17:56:04.616777+00:00'
parser: https://github.com/OpenPecha-dev/openpecha-toolkit/blob/231bba39dd1ba393320de82d4d08a604aabe80fc/openpecha/formatters/google_orc.py
source_metadata:
  id: bdr:W1PD95807
  title: འདུལ་བ་བདུད་རྩིའི་ཉིང་ཁུ
  author: ''
  access: http://purl.bdrc.io/admindata/AccessOpen
  restrictedInChina: false
  base:
    D497:
      image_group_id: I1PD95832
      title: Volume 1 of 'dul ba bdud rts'i nying khu
      total_pages: 390
      order: 1
      base_file: D497.txt
statistics: {}
quality: {}
copyright:
  status: Unknown
  notice: ''
  info_url: null
license: null
